#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM by displaying "I am invincible!!!"

# Trap SIGTERM signal and display message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
