#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM by displaying "I am invincible!!!"

# Set up signal handler for SIGTERM
trap 'echo "I am invincible!!!"' 15

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
